# Last updated: 2/16/2024 23:40
name: kilojoule-environment
channels:
  - conda-forge
dependencies:
  - python = 3.11
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - git+https://github.com/johnfmaddox/kilojoule@devel
